# Generated by Django 6.0 on 2025-12-25 02:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='NIK harus 16 digit angka.', regex='^\\d{16}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='no_wa',
            field=models.CharField(blank=True, help_text='Contoh: 081234567890 atau +6281234567890', max_length=16, validators=[django.core.validators.RegexValidator(message='No WA harus angka (boleh diawali +), panjang 9-15 digit.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
