# Generated by Django 6.0 on 2025-12-25 05:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_nik_alter_user_no_wa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('SKTM', 'Surat Keterangan Tidak Mampu'), ('DOMISILI', 'Surat Keterangan Domisili'), ('BELUM_MENIKAH', 'Surat Keterangan Belum Menikah'), ('SKCK', 'Surat Pengantar SKCK')], max_length=20)),
                ('status', models.CharField(choices=[('DIPROSES', 'Dalam Proses'), ('DISETUJUI', 'Disetujui'), ('TELAH_DIAMBIL', 'Telah Diambil'), ('DITOLAK', 'Ditolak')], default='DIPROSES', max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('nik', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='NIK harus 16 digit angka.', regex='^\\d{16}$')])),
                ('alamat', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='letter_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
